<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="resourceStyle.xsl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="resourceSchema.xsd" ?>

<!DOCTYPE list [
    <!ELEMENT list (resource)+>
    <!ELEMENT resource (Title,Id,Content,Timestamp)>
    <!ELEMENT Title (#PCDATA)>
    <!ELEMENT Id (#PCDATA)>
    <!ELEMENT Content (#PCDATA)>
    <!ELEMENT Timestamp (#PCDATA)>
]>

<list>
    <resource>
        <Title>Resource Link</Title>
        <Id>1</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>2</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>3</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>4</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>5</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>6</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>7</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>8</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>9</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
    <resource>
        <Title>Resource Link</Title>
        <Id>10</Id>
        <Content>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum excepturi, inventore eveniet asperiores dignissimos officiis pariatur et!
        </Content>
        <Timestamp>3.2</Timestamp>
    </resource>
</list>